from enum import Enum

class FacetErrorCode(str, Enum):
    ALLERGEN_CONFLICT = "ALLERGEN_CONFLICT"
    CAPABILITY_NOT_GRANTED = "CAPABILITY_NOT_GRANTED"
    FORBIDDEN = "FORBIDDEN"
    FULFILLMENT_REQUIRED = "FULFILLMENT_REQUIRED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVENTORY_UNAVAILABLE = "INVENTORY_UNAVAILABLE"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    NOT_FOUND = "NOT_FOUND"
    PROHIBITED_GOODS = "PROHIBITED_GOODS"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    RATE_LIMITED = "RATE_LIMITED"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    UNDELIVERABLE = "UNDELIVERABLE"
    VERSION_NOT_SUPPORTED = "VERSION_NOT_SUPPORTED"

    def __str__(self) -> str:
        return str(self.value)
