export { FacetClient } from "./client.ts";
export type {
  CheckoutRequest,
  FacetClientOptions,
  KyaTokenProvider,
  RequestOptions,
} from "./client.ts";
export { FacetClientError, FacetTransportError, isFacetErrorEnvelope } from "./errors.ts";
export { verifyWebhookDelivery } from "./webhook.ts";
export type { VerifyWebhookOptions, VerifyWebhookResult } from "./webhook.ts";

// Re-export wire types so SDK consumers can import everything from one place.
export type {
  CancelReservationRequest,
  CancelReservationResponse,
  CapabilitiesResponse,
  CatalogChange,
  CatalogChangeAction,
  CatalogChangeKind,
  CatalogChangesSinceRequest,
  CatalogChangesSinceResponse,
  CheckoutCompleteRequest,
  CheckoutCompleteResponse,
  CheckoutCreateRequest,
  CheckoutCreateResponse,
  CheckoutCredential,
  CheckoutLineItem,
  CheckoutOrderRef,
  CheckoutPayment,
  CheckoutPaymentInstrument,
  DeleteWebhookRequest,
  DeleteWebhookResponse,
  Document,
  DocumentKind,
  EscalationStatus,
  EscalationTicket,
  FacetErrorBody,
  FacetErrorCode,
  FacetErrorEnvelope,
  FacetErrorSuggest,
  FacetRateLimitState,
  GetDocumentRequest,
  GetDocumentResponse,
  GetOrderRequest,
  GetOrderResponse,
  GetProductRequest,
  GetProductResponse,
  HealthResponse,
  IdentifyResponse,
  ListWebhooksResponse,
  Order,
  OrderHistoryRequest,
  OrderHistoryResponse,
  OrderLineItem,
  OrderStatus,
  Product,
  QuoteRequest,
  QuoteResponse,
  Refund,
  RefundRequestRequest,
  RefundRequestResponse,
  RefundStatus,
  ReputationRequest,
  ReputationResponse,
  ReputationTier,
  RequestHumanRequest,
  RequestHumanResponse,
  ReserveRequest,
  ReserveResponse,
  SearchProductResult,
  SearchRequest,
  SearchResponse,
  SessionExtendRequest,
  SettleRequest,
  SettleResponse,
  SubscribeWebhookRequest,
  SubscribeWebhookResponse,
  TermsResponse,
  VersionResponse,
  WebhookDeliveryEnvelope,
  WebhookEvent,
  WebhookSubscription,
  WhoamiResponse,
} from "@facet-llc/adapter";
export {
  FACET_PROTOCOL_VERSION,
  HEADER_WEBHOOK_DELIVERY_ID,
  HEADER_WEBHOOK_EVENT,
  HEADER_WEBHOOK_SIGNATURE,
  MCP_PROTOCOL_VERSION,
  WEBHOOK_EVENTS,
} from "@facet-llc/adapter";
