export { AgentsTxtError, parseAgentsTxt } from "./agents-txt.ts";
export type { AgentsTxt, ParseOptions } from "./agents-txt.ts";

export { STRIPE_PRICE_TO_TIER, SUBSCRIPTION_TIERS } from "./subscription-tiers.ts";
export type { SubscriptionTier, SubscriptionTierDefinition } from "./subscription-tiers.ts";

export {
  FACET_PROTOCOL_VERSION,
  HEADER_FACET_SIGNATURE,
  HEADER_IDEMPOTENCY_KEY,
  HEADER_RATE_LIMIT_LIMIT,
  HEADER_RATE_LIMIT_REMAINING,
  HEADER_RATE_LIMIT_RESET,
  HEADER_RETRY_AFTER,
  HEADER_TRACE_ID,
  HEADER_WEBHOOK_DELIVERY_ID,
  HEADER_WEBHOOK_EVENT,
  HEADER_WEBHOOK_SIGNATURE,
  MCP_FIRST_MODERN_VERSION,
  MCP_LATEST_LEGACY_VERSION,
  MCP_LATEST_VERSION,
  MCP_PROTOCOL_VERSION,
  MCP_SUPPORTED_VERSIONS,
  PROOF_KINDS,
  WEBHOOK_EVENTS,
} from "./terminal-types.ts";
export type {
  BuyerProtectionBonded,
  CalendlyWebhookAckConfirmed,
  CalendlyWebhookAckIgnored,
  CalendlyWebhookAckNoMatch,
  CalendlyWebhookRateLimited,
  CalendlyWebhookResponse,
  CancelOrderRequest,
  CancelOrderResponse,
  CancelReservationRequest,
  CancelReservationResponse,
  CapabilitiesResponse,
  CapabilityDisabledEntry,
  CatalogChange,
  CatalogChangeAction,
  CatalogChangeKind,
  CatalogChangesSinceRequest,
  CatalogChangesSinceResponse,
  CheckoutCompleteRequest,
  CheckoutCompleteResponse,
  CheckoutCreateRequest,
  CheckoutCreateResponse,
  CheckoutCredential,
  CheckoutLineItem,
  CheckoutOrderRef,
  CheckoutPayment,
  CheckoutPaymentInstrument,
  ComplianceCertification,
  ComplianceDocument,
  ComplianceOverride,
  ConsumeLicenseRequest,
  ConsumeLicenseResponse,
  CreateComplianceRequest,
  CreateComplianceResponse,
  CreateDocumentRequest,
  CreateDocumentResponse,
  DeleteComplianceRequest,
  DeleteComplianceResponse,
  DeleteDocumentRequest,
  DeleteDocumentResponse,
  DeleteWebhookRequest,
  DeleteWebhookResponse,
  DisputeRuling,
  DisputeRulingOutcome,
  Document,
  DocumentKind,
  EscalationStatus,
  EscalationTicket,
  ExtendReservationRequest,
  ExtendReservationResponse,
  FacetErrorBody,
  FacetErrorCode,
  FacetErrorEnvelope,
  FacetErrorSuggest,
  FacetKeyBundle,
  FacetPublicKey,
  FacetRateLimitState,
  GetComplianceRequest,
  GetComplianceResponse,
  GetDocumentRequest,
  GetDocumentResponse,
  GetLicenseRequest,
  GetLicenseResponse,
  GetOrderRequest,
  GetOrderResponse,
  GetProductRequest,
  GetProductResponse,
  GetReceiptRequest,
  GetReceiptResponse,
  WalletReceiptAuth,
  GetSignaturesRequest,
  GetSignaturesResponse,
  OrderSignatureRecord,
  OrderAuthorizationRecord,
  GetRefundRequest,
  GetRefundResponse,
  GetReservationRequest,
  GetReservationResponse,
  GetSettlementRequest,
  GetSettlementResponse,
  GetWebhookRequest,
  GetWebhookResponse,
  HealthResponse,
  HelloResponse,
  IdentifyResponse,
  License,
  LicenseOffer,
  ListComplianceRequest,
  ListComplianceResponse,
  ListDocumentRequest,
  ListDocumentResponse,
  ListLicensesRequest,
  ListLicensesResponse,
  ListRefundsRequest,
  ListRefundsResponse,
  ListReservationsRequest,
  ListReservationsResponse,
  ListSessionsResponse,
  ListSettlementsRequest,
  ListSettlementsResponse,
  ListWebhooksResponse,
  MppChargeRequest,
  MppChargeResponse,
  MppProblem,
  MsIdentityAssociatedApplication,
  MsIdentityAssociationResponse,
  OmsPushOrderRequest,
  OmsPushOrderResponse,
  OmsPushRefundRequest,
  OmsPushRefundResponse,
  Order,
  OrderHistoryRequest,
  OrderHistoryResponse,
  OrderLineItem,
  OrderStatus,
  PricingSchedule,
  PricingTier,
  Product,
  ProductCompliance,
  PromoSlotsResponse,
  ProofKind,
  PurchaseLicenseRequest,
  PurchaseLicenseResponse,
  QuoteAmountInUom,
  QuoteLicenseRequest,
  QuoteLicenseResponse,
  QuoteRequest,
  QuoteResponse,
  ReadyCheckStatus,
  ReadyResponse,
  ShippingTarget,
  FulfillmentInput,
  SkuKind,
  Shipment,
  ReceiptEnvelopeEntry,
  ReconcileSettlementOutcome,
  ReconcileSettlementResult,
  ReconcileSettlementsRequest,
  ReconcileSettlementsResponse,
  Refund,
  RefundAdjudicateRequest,
  RefundDecideRequest,
  RefundEscalateRequest,
  RefundEscalateResponse,
  RefundLineItem,
  RefundRequestRequest,
  RefundRequestResponse,
  RefundStatus,
  ReputationRequest,
  ReputationResponse,
  ReputationTier,
  RequestHumanRequest,
  RequestHumanResponse,
  Reservation,
  ReservationStatus,
  ReserveRequest,
  ReserveResponse,
  RevokeLicenseRequest,
  RevokeLicenseResponse,
  RevokeSessionRequest,
  RevokeSessionResponse,
  SearchProductResult,
  SearchRequest,
  SearchResponse,
  SessionExtendRequest,
  SessionExtendResponse,
  SessionSummary,
  OrderAttributes,
  Settlement,
  SettlementState,
  SettleRequest,
  SettleResponse,
  SubmitProofAttestationRequest,
  SubmitProofAttestationResponse,
  AgentAttestation,
  AttestationParty,
  AttestationResponse,
  AttestFulfillmentRequest,
  AttestReceiptRequest,
  MerchantAttestation,
  RegisterAttestationKeyRequest,
  RegisterAttestationKeyResponse,
  RevokeAttestationKeyRequest,
  RevokeAttestationKeyResponse,
  SubscribeWebhookRequest,
  SubscribeWebhookResponse,
  TermsResponse,
  UpdateComplianceRequest,
  UpdateComplianceResponse,
  UpdateDocumentRequest,
  UpdateDocumentResponse,
  UpdateOrderRequest,
  UpdateOrderResponse,
  UpdateWebhookRequest,
  UpdateWebhookResponse,
  VersionResponse,
  WebhookDeliveryEnvelope,
  WebhookEvent,
  WebhookSubscription,
  WhoamiResponse,
  WishlistAddRequest,
  WishlistAddResponse,
  WishlistItem,
  WishlistListRequest,
  WishlistListResponse,
  WishlistRemoveRequest,
  WishlistRemoveResponse,
} from "./terminal-types.ts";

export type {
  BuildRequirementsInput,
  BuildRequirementsOk,
  CaptureInput,
  CaptureOk,
  DisputeInput,
  DisputeOk,
  FacetPaymentRailAdapter,
  MerchantConfig,
  MoneyAmount,
  RailAdapterMetadata,
  RailAdapterResult,
  RailId,
  RailRequestContext,
  RefundInput,
  RefundOk,
  ReserveAuthorityInput,
  ReserveAuthorityOk,
  VerifyAuthorityInput,
  VerifyAuthorityOk,
  WebhookOutcome,
  WebhookRequest,
} from "./rail-adapter.ts";

export type {
  AgentPrincipal,
  AttestationKind,
  FacetOriginationVerifier,
  OriginationVerifierId,
  OriginationVerifierMetadata,
  VerifyAttestationInput,
  VerifyAttestationResult,
} from "./origination-verifier.ts";

// ─────────────────────────────────────────────────────────────────────────────
// Per-primitive type modules
// ─────────────────────────────────────────────────────────────────────────────

export type {
  AdapterSlot,
  BookingAttendee,
  CancelBookingRequest,
  CancelBookingResponse,
  CancelBookingResult,
  ConfirmBookingRequest,
  ConfirmBookingResponse,
  ConfirmBookingResult,
  DateRange,
  FindSlotsRequest,
  FindSlotsResponse,
  HoldSlotRequest,
  HoldSlotResponse,
  HoldSlotResult,
  ModifyBookingRequest,
  ModifyBookingResponse,
  ModifyBookingResult,
} from "./booking-types.ts";

export type {
  CancelSubscriptionRequest,
  CancelSubscriptionResponse,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  FindInventoryRequest,
  FindInventoryResponse,
  InventoryUnit,
  ModifySubscriptionLinesRequest,
  ModifySubscriptionLinesResponse,
  PauseSubscriptionRequest,
  PauseSubscriptionResponse,
  SkipNextRunRequest,
  SkipNextRunResponse,
  SubscriptionLineItem,
  SubscriptionProfile,
  SubscriptionProfileResponse,
  SubscriptionStatus,
} from "./subscription-types.ts";

export type {
  AcceptQuoteRequest,
  AcceptQuoteResponse,
  CancelRfqRequest,
  CancelRfqResponse,
  CounterQuoteRequest,
  CounterQuoteResponse,
  GetRfqStatusRequest,
  GetRfqStatusResponse,
  RfqAttachment,
  RfqQuote,
  RfqQuoteStatus,
  RfqRequest,
  RfqRequestStatus,
  SubmitRfqRequest,
  SubmitRfqResponse,
} from "./rfq-types.ts";

export type {
  AuctionRow,
  AuctionStatus,
  BidSummary,
  GetAuctionRequest,
  GetAuctionResponse,
  GetBidStatusRequest,
  GetBidStatusResponse,
  ListAuctionsRequest,
  ListAuctionsResponse,
  PlaceBidRequest,
  PlaceBidResponse,
  PublicAuction,
} from "./auction-types.ts";

export type {
  GraphMatchRequest,
  GraphMatchResponse,
  GraphPathQueryParams,
  GraphPathResponse,
  GraphRelatedQueryParams,
  GraphRelatedResponse,
  KgNodeType,
  KgRelation,
  MatchHit,
  RelatedEdge,
  RelatedNode,
} from "./graph-types.ts";

export type {
  DiscoverEdge,
  DiscoverHandoff,
  DiscoverNear,
  DiscoverProductResult,
  DiscoverProductsRequest,
  DiscoverProductsResponse,
  DiscoverReputation,
  DiscoverRequest,
  DiscoverResponse,
  DiscoverResult,
  VisualSearchRequest,
  VisualSearchResponse,
  VisualSearchResult,
} from "./discover-types.ts";

export {
  FACET_DISCOVER_TOOL,
  FACET_GET_MERCHANT_TOOL,
  FACET_MCP_TOOLS,
  FACET_QUOTE_TOOL,
  FACET_SEARCH_PRODUCTS_TOOL,
} from "./mcp-tools.ts";
export type { FacetMcpToolDefinition } from "./mcp-tools.ts";

export type {
  CaptureDispatch,
  DispatchAgentSummary,
  DisputeDispatch,
  HandleWebhookDispatch,
  PaymentsCapabilitiesResponse,
  PaymentsDispatchOp,
  PaymentsDispatchRequest,
  PaymentsDispatchRequestBase,
  PaymentsDispatchResponse,
  PaymentsRouteRequest,
  PaymentsRouteResponse,
  RefundDispatch,
  ReserveAuthorityDispatch,
  VerifyAuthorityDispatch,
} from "./payment-dispatch-types.ts";

export type {
  StripeBalanceAmount,
  StripeBalanceRequest,
  StripeBalanceResponse,
  StripeCheckoutSessionRequest,
  StripeCheckoutSessionResponse,
  StripeOnboardingLinkRequest,
  StripeOnboardingLinkResponse,
  StripeWebhookAck,
  StripeWebhookAckCheckoutCompleted,
  StripeWebhookAckIgnored,
  StripeWebhookAckLicense,
  StripeWebhookAckModeMismatch,
  StripeWebhookAckSubscriptionDeleted,
  StripeWebhookAckSubscriptionUpdated,
} from "./stripe-types.ts";

export type {
  VerificationMethod,
  VerifyDomainOutcome,
  VerifyDomainRequest,
  VerifyDomainResponse,
} from "./verify-domain-types.ts";

// FacetManifest is the structure of the YAML payload served by
// /v1/schema (and the upcoming /v1/catalog-manifest.yaml). The
// authoritative definition lives in @facet-llc/schema-generator-core;
// we re-document the type-name here only as guidance for downstream
// consumers — re-exporting across packages would create a circular
// devDependency chain. Pull directly from
// @facet-llc/schema-generator-core when you need the manifest shape.
